### ISSUE TITLE
Track1: Could you release the upper-bound performance(average mAP) during each experience? 

### ISSUE THREAD

**Issue by ppppeng** [ContinualAI/clvision-challenge-2022#15]

**Comment by lrzpellegrini** [comment]
Hi @ppppeng, regarding the upper bound for track 2 I answered [here](https://github.com/ContinualAI/clvision-challenge-2022/issues/12).

For tracks 3 and 1:

After task 0: `0.2`
After task 1: `0.4`
After task 2: `0.6`
After task 3: `0.8`
After task 4: `1.0`

because each image has only the annotation for a single main object + each experience contains only a subset of objects which are not seen again in other experiences.

This means that, for tracks 3 and 1, the overall upper bound is `0.6`: average mAP for track 3 (instance detection), average mean class accuracy [AMCA] for track 1 (instance classification).

We will ask top-ranking participants to send us their code to check if their solution is aligned with the rules. However, we do so only at the end of the submission phase, which ends on the 29th of May.

**Comment by lrzpellegrini** [comment]
Sorry, my bad. The track 1 upper bound is `0.533333`, not `0.6`, because the classification track features 15 experiences instead of 5.

**Comment by Layjins** [comment]
> Hi @ppppeng, regarding the upper bound for track 2 I answered [here](https://github.com/ContinualAI/clvision-challenge-2022/issues/12).
> 
> For tracks 3 and 1:
> 
> After task 0: `0.2` After task 1: `0.4` After task 2: `0.6` After task 3: `0.8` After task 4: `1.0`
> 
> because each image has only the annotation for a single main object + each experience contains only a subset of objects which are not seen again in other experiences.
> 
> This means that, for tracks 3 and 1, the overall upper bound is `0.6`: average mAP for track 3 (instance detection), average mean class accuracy [AMCA] for track 1 (instance classification).
> 
> We will ask top-ranking participants to send us their code to check if their solution is aligned with the rules. However, we do so only at the end of the submission phase, which ends on the 29th of May.

Specifically, for tracks 3:
After task 0: `0.2261=251/1110`
After task 1: `0.4162=(251+211)/1110`
After task 2: `0.6243=(251+211+231)/1110`
After task 3: `0.8342=(251+211+231+233)/1110`
After task 4: `1.0=(251+211+231+233+184)/1110`
